pub static INITIALS: [&'static str; 128] = [
    "",      // (none)
    "S",     // S
    "T",     // T
    "ST",    // ST
    "K",     // K
    "SK",    // SK
    "D",     // TK
    "SD",    // STK
    "P",     // P
    "SP",    // SP
    "F",     // TP
    "SF",    // STP
    "X",     // KP
    "SKP",   // SKP
    "DP",    // TKP
    "SDP",   // STKP
    "W",     // W
    "SW",    // SW
    "TW",    // TW
    "STW",   // STW
    "KW",    // KW
    "SKW",   // SKW
    "DW",    // TKW
    "SDW",   // STKW
    "B",     // PW
    "SB",    // SPW
    "TB",    // TPW
    "STB",   // STPW
    "KB",    // KPW
    "SKB",   // SKPW
    "G",     // TKPW
    "SG",    // STKPW
    "H",     // H
    "SH",    // SH
    "TH",    // TH
    "STH",   // STH
    "Ch",    // KH
    "SKH",   // SKH
    "DH",    // TKH
    "SDH",   // STKH
    "M",     // PH
    "SM",    // SPH
    "N",     // TPH
    "SN",    // STPH
    "KM",    // KPH
    "SKM",   // SKPH
    "DM",    // TKPH
    "SDM",   // STKPH
    "WH",    // WH
    "SWH",   // SWH
    "TWH",   // TWH
    "STWH",  // STWH
    "KWH",   // KWH
    "SKWH",  // SKWH
    "DWH",   // TKWH
    "SDWH",  // STKWH
    "BH",    // PWH
    "SBH",   // SPWH
    "TBH",   // TPWH
    "STBH",  // STPWH
    "KBH",   // KPWH
    "SKBH",  // SKPWH
    "GH",    // TKPWH
    "SGH",   // STKPWH
    "R",     // R
    "V",     // SR
    "TR",    // TR
    "STR",   // STR
    "KR",    // KR
    "SKR",   // SKR
    "DR",    // TKR
    "SDR",   // STKR
    "PR",    // PR
    "SPR",   // SPR
    "FR",    // TPR
    "SFR",   // STPR
    "KPR",   // KPR
    "SKPR",  // SKPR
    "DPR",   // TKPR
    "SDPR",  // STKPR
    "WR",    // WR
    "SWR",   // SWR
    "TWR",   // TWR
    "STWR",  // STWR
    "Y",     // KWR
    "J",     // SKWR
    "DWR",   // TKWR
    "SDWR",  // STKWR
    "BR",    // PWR
    "SBR",   // SPWR
    "TBR",   // TPWR
    "STBR",  // STPWR
    "KBR",   // KPWR
    "SKBR",  // SKPWR
    "GR",    // TKPWR
    "SGR",   // STKPWR
    "L",     // HR
    "SL",    // SHR
    "TL",    // THR
    "STL",   // STHR
    "KL",    // KHR
    "SKL",   // SKHR
    "DL",    // TKHR
    "SDL",   // STKHR
    "PL",    // PHR
    "SPL",   // SPHR
    "FL",    // TPHR
    "SFL",   // STPHR
    "KPL",   // KPHR
    "SKPL",  // SKPHR
    "DPL",   // TKPHR
    "SDPL",  // STKPHR
    "WL",    // WHR
    "SWL",   // SWHR
    "TWL",   // TWHR
    "STWL",  // STWHR
    "KWL",   // KWHR
    "SKWL",  // SKWHR
    "DWL",   // TKWHR
    "SDWL",  // STKWHR
    "BL",    // PWHR
    "SBL",   // SPWHR
    "TBL",   // TPWHR
    "STBL",  // STPWHR
    "KBL",   // KPWHR
    "SKBL",  // SKPWHR
    "GL",    // TKPWHR
    "SGL",   // STKPWHR
];

pub static MIDDLES: [&'static str; 32] = [
    "",      // (none)
    "A",     // A
    "O",     // O
    "Oo",    // AO
    "*",     // *
    "A*",    // A*
    "O*",    // O*
    "Oo*",   // AO*
    "E",     // E
    "Ea",    // AE
    "Oh",    // OE
    "Ee",    // AOE
    "E*",    // *E
    "Ea*",   // A*E
    "Oh*",   // O*E
    "Ee*",   // AO*E
    "U",     // U
    "Aw",    // AU
    "OU",    // OU
    "Yoo",   // AOU
    "U*",    // *U
    "Aw*",   // A*U
    "OU*",   // O*U
    "Yoo*",  // AO*U
    "I",     // EU
    "Ay",    // AEU
    "Oy",    // OEU
    "Eye",   // AOEU
    "I*",    // *EU
    "Ay*",   // A*EU
    "Oy*",   // O*EU
    "Eye*",  // AO*EU
];

pub static FINALS: [&'static str; 1024] = [
    "",            // (none)
    "F",           // F
    "R",           // R
    "FR",          // FR
    "P",           // P
    "Ch",          // FP
    "RP",          // RP
    "FRP",         // FRP
    "B",           // B
    "FB",          // FB
    "Sh",          // RB
    "FRB",         // FRB
    "N",           // PB
    "FPB",         // FPB
    "RPB",         // RPB
    "FRPB",        // FRPB
    "L",           // L
    "FL",          // FL
    "RL",          // RL
    "FRL",         // FRL
    "M",           // PL
    "Ism",         // FPL
    "RPL",         // RPL
    "FRPL",        // FRPL
    "BL",          // BL
    "FBL",         // FBL
    "RBL",         // RBL
    "FRBL",        // FRBL
    "PBL",         // PBL
    "FPBL",        // FPBL
    "RPBL",        // RPBL
    "FRPBL",       // FRPBL
    "G",           // G
    "FG",          // FG
    "RG",          // RG
    "FRG",         // FRG
    "PG",          // PG
    "FPG",         // FPG
    "RPG",         // RPG
    "FRPG",        // FRPG
    "Ck",          // BG
    "FCk",         // FBG
    "Rk",          // RBG
    "FRBG",        // FRBG
    "NG",          // PBG
    "FPBG",        // FPBG
    "RPBG",        // RPBG
    "FRPBG",       // FRPBG
    "LG",          // LG
    "FLG",         // FLG
    "RLG",         // RLG
    "FRLG",        // FRLG
    "PLG",         // PLG
    "FPLG",        // FPLG
    "RPLG",        // RPLG
    "FRPLG",       // FRPLG
    "BLG",         // BLG
    "FBLG",        // FBLG
    "RBLG",        // RBLG
    "FRBLG",       // FRBLG
    "J",           // PBLG
    "FPBLG",       // FPBLG
    "RJ",          // RPBLG
    "FRPBLG",      // FRPBLG
    "T",           // T
    "FT",          // FT
    "RT",          // RT
    "FRT",         // FRT
    "PT",          // PT
    "FPT",         // FPT
    "RPT",         // RPT
    "FRPT",        // FRPT
    "BT",          // BT
    "FBT",         // FBT
    "RBT",         // RBT
    "FRBT",        // FRBT
    "NT",          // PBT
    "FPBT",        // FPBT
    "RPBT",        // RPBT
    "FRPBT",       // FRPBT
    "LT",          // LT
    "FLT",         // FLT
    "RLT",         // RLT
    "FRLT",        // FRLT
    "Ment",        // PLT
    "FPLT",        // FPLT
    "RPLT",        // RPLT
    "FRPLT",       // FRPLT
    "BLT",         // BLT
    "FBLT",        // FBLT
    "RBLT",        // RBLT
    "FRBLT",       // FRBLT
    "PBLT",        // PBLT
    "FPBLT",       // FPBLT
    "RPBLT",       // RPBLT
    "FRPBLT",      // FRPBLT
    "GT",          // GT
    "FGT",         // FGT
    "RGT",         // RGT
    "FRGT",        // FRGT
    "PGT",         // PGT
    "FPGT",        // FPGT
    "RPGT",        // RPGT
    "FRPGT",       // FRPGT
    "CkT",         // BGT
    "FBGT",        // FBGT
    "RBGT",        // RBGT
    "FRBGT",       // FRBGT
    "PBGT",        // PBGT
    "FPBGT",       // FPBGT
    "RPBGT",       // RPBGT
    "FRPBGT",      // FRPBGT
    "LGT",         // LGT
    "FLGT",        // FLGT
    "RLGT",        // RLGT
    "FRLGT",       // FRLGT
    "PLGT",        // PLGT
    "FPLGT",       // FPLGT
    "RPLGT",       // RPLGT
    "FRPLGT",      // FRPLGT
    "BLGT",        // BLGT
    "FBLGT",       // FBLGT
    "RBLGT",       // RBLGT
    "FRBLGT",      // FRBLGT
    "PBLGT",       // PBLGT
    "FPBLGT",      // FPBLGT
    "RPBLGT",      // RPBLGT
    "FRPBLGT",     // FRPBLGT
    "S",           // S
    "FS",          // FS
    "RS",          // RS
    "FRS",         // FRS
    "PS",          // PS
    "FPS",         // FPS
    "RPS",         // RPS
    "FRPS",        // FRPS
    "BS",          // BS
    "FBS",         // FBS
    "RBS",         // RBS
    "FRBS",        // FRBS
    "NS",          // PBS
    "FPBS",        // FPBS
    "RPBS",        // RPBS
    "FRPBS",       // FRPBS
    "LS",          // LS
    "FLS",         // FLS
    "RLS",         // RLS
    "FRLS",        // FRLS
    "PLS",         // PLS
    "FPLS",        // FPLS
    "RPLS",        // RPLS
    "FRPLS",       // FRPLS
    "BLS",         // BLS
    "FBLS",        // FBLS
    "RBLS",        // RBLS
    "FRBLS",       // FRBLS
    "PBLS",        // PBLS
    "FPBLS",       // FPBLS
    "RPBLS",       // RPBLS
    "FRPBLS",      // FRPBLS
    "Tion",        // GS
    "FGS",         // FGS
    "RTion",       // RGS
    "FRGS",        // FRGS
    "PGS",         // PGS
    "FPGS",        // FPGS
    "RPGS",        // RPGS
    "FRPGS",       // FRPGS
    "CkS",         // BGS
    "FBGS",        // FBGS
    "RBGS",        // RBGS
    "FRBGS",       // FRBGS
    "PBGS",        // PBGS
    "FPBGS",       // FPBGS
    "RPBGS",       // RPBGS
    "FRPBGS",      // FRPBGS
    "LGS",         // LGS
    "FLGS",        // FLGS
    "RLGS",        // RLGS
    "FRLGS",       // FRLGS
    "PLGS",        // PLGS
    "FPLGS",       // FPLGS
    "RPLGS",       // RPLGS
    "FRPLGS",      // FRPLGS
    "BLGS",        // BLGS
    "FBLGS",       // FBLGS
    "RBLGS",       // RBLGS
    "FRBLGS",      // FRBLGS
    "JS",       // PBLGS
    "FPBLGS",      // FPBLGS
    "RPBLGS",      // RPBLGS
    "FRPBLGS",     // FRPBLGS
    "TS",          // TS
    "FTS",         // FTS
    "RTS",         // RTS
    "FRTS",        // FRTS
    "PTS",         // PTS
    "FPTS",        // FPTS
    "RPTS",        // RPTS
    "FRPTS",       // FRPTS
    "BTS",         // BTS
    "FBTS",        // FBTS
    "RBTS",        // RBTS
    "FRBTS",       // FRBTS
    "NTS",         // PBTS
    "FPBTS",       // FPBTS
    "RPBTS",       // RPBTS
    "FRPBTS",      // FRPBTS
    "LTS",         // LTS
    "FLTS",        // FLTS
    "RLTS",        // RLTS
    "FRLTS",       // FRLTS
    "PLTS",        // PLTS
    "FPLTS",       // FPLTS
    "RPLTS",       // RPLTS
    "FRPLTS",      // FRPLTS
    "BLTS",        // BLTS
    "FBLTS",       // FBLTS
    "RBLTS",       // RBLTS
    "FRBLTS",      // FRBLTS
    "PBLTS",       // PBLTS
    "FPBLTS",      // FPBLTS
    "RPBLTS",      // RPBLTS
    "FRPBLTS",     // FRPBLTS
    "GTS",         // GTS
    "FGTS",        // FGTS
    "RGTS",        // RGTS
    "FRGTS",       // FRGTS
    "PGTS",        // PGTS
    "FPGTS",       // FPGTS
    "RPGTS",       // RPGTS
    "FRPGTS",      // FRPGTS
    "BGTS",        // BGTS
    "FBGTS",       // FBGTS
    "RBGTS",       // RBGTS
    "FRBGTS",      // FRBGTS
    "PBGTS",       // PBGTS
    "FPBGTS",      // FPBGTS
    "RPBGTS",      // RPBGTS
    "FRPBGTS",     // FRPBGTS
    "LGTS",        // LGTS
    "FLGTS",       // FLGTS
    "RLGTS",       // RLGTS
    "FRLGTS",      // FRLGTS
    "PLGTS",       // PLGTS
    "FPLGTS",      // FPLGTS
    "RPLGTS",      // RPLGTS
    "FRPLGTS",     // FRPLGTS
    "BLGTS",       // BLGTS
    "FBLGTS",      // FBLGTS
    "RBLGTS",      // RBLGTS
    "FRBLGTS",     // FRBLGTS
    "PBLGTS",      // PBLGTS
    "FPBLGTS",     // FPBLGTS
    "RPBLGTS",     // RPBLGTS
    "FRPBLGTS",    // FRPBLGTS
    "D",           // D
    "FD",          // FD
    "RD",          // RD
    "FRD",         // FRD
    "PD",          // PD
    "FPD",         // FPD
    "RPD",         // RPD
    "FRPD",        // FRPD
    "BD",          // BD
    "FBD",         // FBD
    "RBD",         // RBD
    "FRBD",        // FRBD
    "ND",          // PBD
    "FPBD",        // FPBD
    "RPBD",        // RPBD
    "FRPBD",       // FRPBD
    "LD",          // LD
    "FLD",         // FLD
    "RLD",         // RLD
    "FRLD",        // FRLD
    "PLD",         // PLD
    "FPLD",        // FPLD
    "RPLD",        // RPLD
    "FRPLD",       // FRPLD
    "BLD",         // BLD
    "FBLD",        // FBLD
    "RBLD",        // RBLD
    "FRBLD",       // FRBLD
    "PBLD",        // PBLD
    "FPBLD",       // FPBLD
    "RPBLD",       // RPBLD
    "FRPBLD",      // FRPBLD
    "GD",          // GD
    "FGD",         // FGD
    "RGD",         // RGD
    "FRGD",        // FRGD
    "PGD",         // PGD
    "FPGD",        // FPGD
    "RPGD",        // RPGD
    "FRPGD",       // FRPGD
    "BGD",         // BGD
    "FBGD",        // FBGD
    "RBGD",        // RBGD
    "FRBGD",       // FRBGD
    "PBGD",        // PBGD
    "FPBGD",       // FPBGD
    "RPBGD",       // RPBGD
    "FRPBGD",      // FRPBGD
    "LGD",         // LGD
    "FLGD",        // FLGD
    "RLGD",        // RLGD
    "FRLGD",       // FRLGD
    "PLGD",        // PLGD
    "FPLGD",       // FPLGD
    "RPLGD",       // RPLGD
    "FRPLGD",      // FRPLGD
    "BLGD",        // BLGD
    "FBLGD",       // FBLGD
    "RBLGD",       // RBLGD
    "FRBLGD",      // FRBLGD
    "JD",          // PBLGD
    "FPBLGD",      // FPBLGD
    "RJD",         // RPBLGD
    "FRPBLGD",     // FRPBLGD
    "TD",          // TD
    "FTD",         // FTD
    "RTD",         // RTD
    "FRTD",        // FRTD
    "PTD",         // PTD
    "FPTD",        // FPTD
    "RPTD",        // RPTD
    "FRPTD",       // FRPTD
    "BTD",         // BTD
    "FBTD",        // FBTD
    "RBTD",        // RBTD
    "FRBTD",       // FRBTD
    "NTD",         // PBTD
    "FPBTD",       // FPBTD
    "RPBTD",       // RPBTD
    "FRPBTD",      // FRPBTD
    "LTD",         // LTD
    "FLTD",        // FLTD
    "RLTD",        // RLTD
    "FRLTD",       // FRLTD
    "PLTD",        // PLTD
    "FPLTD",       // FPLTD
    "RPLTD",       // RPLTD
    "FRPLTD",      // FRPLTD
    "BLTD",        // BLTD
    "FBLTD",       // FBLTD
    "RBLTD",       // RBLTD
    "FRBLTD",      // FRBLTD
    "PBLTD",       // PBLTD
    "FPBLTD",      // FPBLTD
    "RPBLTD",      // RPBLTD
    "FRPBLTD",     // FRPBLTD
    "GTD",         // GTD
    "FGTD",        // FGTD
    "RGTD",        // RGTD
    "FRGTD",       // FRGTD
    "PGTD",        // PGTD
    "FPGTD",       // FPGTD
    "RPGTD",       // RPGTD
    "FRPGTD",      // FRPGTD
    "BGTD",        // BGTD
    "FBGTD",       // FBGTD
    "RBGTD",       // RBGTD
    "FRBGTD",      // FRBGTD
    "PBGTD",       // PBGTD
    "FPBGTD",      // FPBGTD
    "RPBGTD",      // RPBGTD
    "FRPBGTD",     // FRPBGTD
    "LGTD",        // LGTD
    "FLGTD",       // FLGTD
    "RLGTD",       // RLGTD
    "FRLGTD",      // FRLGTD
    "PLGTD",       // PLGTD
    "FPLGTD",      // FPLGTD
    "RPLGTD",      // RPLGTD
    "FRPLGTD",     // FRPLGTD
    "BLGTD",       // BLGTD
    "FBLGTD",      // FBLGTD
    "RBLGTD",      // RBLGTD
    "FRBLGTD",     // FRBLGTD
    "PBLGTD",      // PBLGTD
    "FPBLGTD",     // FPBLGTD
    "RPBLGTD",     // RPBLGTD
    "FRPBLGTD",    // FRPBLGTD
    "SD",          // SD
    "FSD",         // FSD
    "RSD",         // RSD
    "FRSD",        // FRSD
    "PSD",         // PSD
    "FPSD",        // FPSD
    "RPSD",        // RPSD
    "FRPSD",       // FRPSD
    "BSD",         // BSD
    "FBSD",        // FBSD
    "RBSD",        // RBSD
    "FRBSD",       // FRBSD
    "PBSD",        // PBSD
    "FPBSD",       // FPBSD
    "RPBSD",       // RPBSD
    "FRPBSD",      // FRPBSD
    "LSD",         // LSD
    "FLSD",        // FLSD
    "RLSD",        // RLSD
    "FRLSD",       // FRLSD
    "PLSD",        // PLSD
    "FPLSD",       // FPLSD
    "RPLSD",       // RPLSD
    "FRPLSD",      // FRPLSD
    "BLSD",        // BLSD
    "FBLSD",       // FBLSD
    "RBLSD",       // RBLSD
    "FRBLSD",      // FRBLSD
    "PBLSD",       // PBLSD
    "FPBLSD",      // FPBLSD
    "RPBLSD",      // RPBLSD
    "FRPBLSD",     // FRPBLSD
    "GSD",         // GSD
    "FGSD",        // FGSD
    "RGSD",        // RGSD
    "FRGSD",       // FRGSD
    "PGSD",        // PGSD
    "FPGSD",       // FPGSD
    "RPGSD",       // RPGSD
    "FRPGSD",      // FRPGSD
    "BGSD",        // BGSD
    "FBGSD",       // FBGSD
    "RBGSD",       // RBGSD
    "FRBGSD",      // FRBGSD
    "PBGSD",       // PBGSD
    "FPBGSD",      // FPBGSD
    "RPBGSD",      // RPBGSD
    "FRPBGSD",     // FRPBGSD
    "LGSD",        // LGSD
    "FLGSD",       // FLGSD
    "RLGSD",       // RLGSD
    "FRLGSD",      // FRLGSD
    "PLGSD",       // PLGSD
    "FPLGSD",      // FPLGSD
    "RPLGSD",      // RPLGSD
    "FRPLGSD",     // FRPLGSD
    "BLGSD",       // BLGSD
    "FBLGSD",      // FBLGSD
    "RBLGSD",      // RBLGSD
    "FRBLGSD",     // FRBLGSD
    "PBLGSD",      // PBLGSD
    "FPBLGSD",     // FPBLGSD
    "RPBLGSD",     // RPBLGSD
    "FRPBLGSD",    // FRPBLGSD
    "TSD",         // TSD
    "FTSD",        // FTSD
    "RTSD",        // RTSD
    "FRTSD",       // FRTSD
    "PTSD",        // PTSD
    "FPTSD",       // FPTSD
    "RPTSD",       // RPTSD
    "FRPTSD",      // FRPTSD
    "BTSD",        // BTSD
    "FBTSD",       // FBTSD
    "RBTSD",       // RBTSD
    "FRBTSD",      // FRBTSD
    "PBTSD",       // PBTSD
    "FPBTSD",      // FPBTSD
    "RPBTSD",      // RPBTSD
    "FRPBTSD",     // FRPBTSD
    "LTSD",        // LTSD
    "FLTSD",       // FLTSD
    "RLTSD",       // RLTSD
    "FRLTSD",      // FRLTSD
    "PLTSD",       // PLTSD
    "FPLTSD",      // FPLTSD
    "RPLTSD",      // RPLTSD
    "FRPLTSD",     // FRPLTSD
    "BLTSD",       // BLTSD
    "FBLTSD",      // FBLTSD
    "RBLTSD",      // RBLTSD
    "FRBLTSD",     // FRBLTSD
    "PBLTSD",      // PBLTSD
    "FPBLTSD",     // FPBLTSD
    "RPBLTSD",     // RPBLTSD
    "FRPBLTSD",    // FRPBLTSD
    "GTSD",        // GTSD
    "FGTSD",       // FGTSD
    "RGTSD",       // RGTSD
    "FRGTSD",      // FRGTSD
    "PGTSD",       // PGTSD
    "FPGTSD",      // FPGTSD
    "RPGTSD",      // RPGTSD
    "FRPGTSD",     // FRPGTSD
    "BGTSD",       // BGTSD
    "FBGTSD",      // FBGTSD
    "RBGTSD",      // RBGTSD
    "FRBGTSD",     // FRBGTSD
    "PBGTSD",      // PBGTSD
    "FPBGTSD",     // FPBGTSD
    "RPBGTSD",     // RPBGTSD
    "FRPBGTSD",    // FRPBGTSD
    "LGTSD",       // LGTSD
    "FLGTSD",      // FLGTSD
    "RLGTSD",      // RLGTSD
    "FRLGTSD",     // FRLGTSD
    "PLGTSD",      // PLGTSD
    "FPLGTSD",     // FPLGTSD
    "RPLGTSD",     // RPLGTSD
    "FRPLGTSD",    // FRPLGTSD
    "BLGTSD",      // BLGTSD
    "FBLGTSD",     // FBLGTSD
    "RBLGTSD",     // RBLGTSD
    "FRBLGTSD",    // FRBLGTSD
    "PBLGTSD",     // PBLGTSD
    "FPBLGTSD",    // FPBLGTSD
    "RPBLGTSD",    // RPBLGTSD
    "FRPBLGTSD",   // FRPBLGTSD
    "Z",           // Z
    "FZ",          // FZ
    "RZ",          // RZ
    "FRZ",         // FRZ
    "PZ",          // PZ
    "FPZ",         // FPZ
    "RPZ",         // RPZ
    "FRPZ",        // FRPZ
    "BZ",          // BZ
    "FBZ",         // FBZ
    "RBZ",         // RBZ
    "FRBZ",        // FRBZ
    "PBZ",         // PBZ
    "FPBZ",        // FPBZ
    "RPBZ",        // RPBZ
    "FRPBZ",       // FRPBZ
    "LZ",          // LZ
    "FLZ",         // FLZ
    "RLZ",         // RLZ
    "FRLZ",        // FRLZ
    "PLZ",         // PLZ
    "FPLZ",        // FPLZ
    "RPLZ",        // RPLZ
    "FRPLZ",       // FRPLZ
    "BLZ",         // BLZ
    "FBLZ",        // FBLZ
    "RBLZ",        // RBLZ
    "FRBLZ",       // FRBLZ
    "PBLZ",        // PBLZ
    "FPBLZ",       // FPBLZ
    "RPBLZ",       // RPBLZ
    "FRPBLZ",      // FRPBLZ
    "GZ",          // GZ
    "FGZ",         // FGZ
    "RGZ",         // RGZ
    "FRGZ",        // FRGZ
    "PGZ",         // PGZ
    "FPGZ",        // FPGZ
    "RPGZ",        // RPGZ
    "FRPGZ",       // FRPGZ
    "BGZ",         // BGZ
    "FBGZ",        // FBGZ
    "RBGZ",        // RBGZ
    "FRBGZ",       // FRBGZ
    "PBGZ",        // PBGZ
    "FPBGZ",       // FPBGZ
    "RPBGZ",       // RPBGZ
    "FRPBGZ",      // FRPBGZ
    "LGZ",         // LGZ
    "FLGZ",        // FLGZ
    "RLGZ",        // RLGZ
    "FRLGZ",       // FRLGZ
    "PLGZ",        // PLGZ
    "FPLGZ",       // FPLGZ
    "RPLGZ",       // RPLGZ
    "FRPLGZ",      // FRPLGZ
    "BLGZ",        // BLGZ
    "FBLGZ",       // FBLGZ
    "RBLGZ",       // RBLGZ
    "FRBLGZ",      // FRBLGZ
    "PBLGZ",       // PBLGZ
    "FPBLGZ",      // FPBLGZ
    "RPBLGZ",      // RPBLGZ
    "FRPBLGZ",     // FRPBLGZ
    "TZ",          // TZ
    "FTZ",         // FTZ
    "RTZ",         // RTZ
    "FRTZ",        // FRTZ
    "PTZ",         // PTZ
    "FPTZ",        // FPTZ
    "RPTZ",        // RPTZ
    "FRPTZ",       // FRPTZ
    "BTZ",         // BTZ
    "FBTZ",        // FBTZ
    "RBTZ",        // RBTZ
    "FRBTZ",       // FRBTZ
    "PBTZ",        // PBTZ
    "FPBTZ",       // FPBTZ
    "RPBTZ",       // RPBTZ
    "FRPBTZ",      // FRPBTZ
    "LTZ",         // LTZ
    "FLTZ",        // FLTZ
    "RLTZ",        // RLTZ
    "FRLTZ",       // FRLTZ
    "PLTZ",        // PLTZ
    "FPLTZ",       // FPLTZ
    "RPLTZ",       // RPLTZ
    "FRPLTZ",      // FRPLTZ
    "BLTZ",        // BLTZ
    "FBLTZ",       // FBLTZ
    "RBLTZ",       // RBLTZ
    "FRBLTZ",      // FRBLTZ
    "PBLTZ",       // PBLTZ
    "FPBLTZ",      // FPBLTZ
    "RPBLTZ",      // RPBLTZ
    "FRPBLTZ",     // FRPBLTZ
    "GTZ",         // GTZ
    "FGTZ",        // FGTZ
    "RGTZ",        // RGTZ
    "FRGTZ",       // FRGTZ
    "PGTZ",        // PGTZ
    "FPGTZ",       // FPGTZ
    "RPGTZ",       // RPGTZ
    "FRPGTZ",      // FRPGTZ
    "BGTZ",        // BGTZ
    "FBGTZ",       // FBGTZ
    "RBGTZ",       // RBGTZ
    "FRBGTZ",      // FRBGTZ
    "PBGTZ",       // PBGTZ
    "FPBGTZ",      // FPBGTZ
    "RPBGTZ",      // RPBGTZ
    "FRPBGTZ",     // FRPBGTZ
    "LGTZ",        // LGTZ
    "FLGTZ",       // FLGTZ
    "RLGTZ",       // RLGTZ
    "FRLGTZ",      // FRLGTZ
    "PLGTZ",       // PLGTZ
    "FPLGTZ",      // FPLGTZ
    "RPLGTZ",      // RPLGTZ
    "FRPLGTZ",     // FRPLGTZ
    "BLGTZ",       // BLGTZ
    "FBLGTZ",      // FBLGTZ
    "RBLGTZ",      // RBLGTZ
    "FRBLGTZ",     // FRBLGTZ
    "PBLGTZ",      // PBLGTZ
    "FPBLGTZ",     // FPBLGTZ
    "RPBLGTZ",     // RPBLGTZ
    "FRPBLGTZ",    // FRPBLGTZ
    "SZ",          // SZ
    "FSZ",         // FSZ
    "RSZ",         // RSZ
    "FRSZ",        // FRSZ
    "PSZ",         // PSZ
    "FPSZ",        // FPSZ
    "RPSZ",        // RPSZ
    "FRPSZ",       // FRPSZ
    "BSZ",         // BSZ
    "FBSZ",        // FBSZ
    "RBSZ",        // RBSZ
    "FRBSZ",       // FRBSZ
    "PBSZ",        // PBSZ
    "FPBSZ",       // FPBSZ
    "RPBSZ",       // RPBSZ
    "FRPBSZ",      // FRPBSZ
    "LSZ",         // LSZ
    "FLSZ",        // FLSZ
    "RLSZ",        // RLSZ
    "FRLSZ",       // FRLSZ
    "PLSZ",        // PLSZ
    "FPLSZ",       // FPLSZ
    "RPLSZ",       // RPLSZ
    "FRPLSZ",      // FRPLSZ
    "BLSZ",        // BLSZ
    "FBLSZ",       // FBLSZ
    "RBLSZ",       // RBLSZ
    "FRBLSZ",      // FRBLSZ
    "PBLSZ",       // PBLSZ
    "FPBLSZ",      // FPBLSZ
    "RPBLSZ",      // RPBLSZ
    "FRPBLSZ",     // FRPBLSZ
    "GSZ",         // GSZ
    "FGSZ",        // FGSZ
    "RGSZ",        // RGSZ
    "FRGSZ",       // FRGSZ
    "PGSZ",        // PGSZ
    "FPGSZ",       // FPGSZ
    "RPGSZ",       // RPGSZ
    "FRPGSZ",      // FRPGSZ
    "BGSZ",        // BGSZ
    "FBGSZ",       // FBGSZ
    "RBGSZ",       // RBGSZ
    "FRBGSZ",      // FRBGSZ
    "PBGSZ",       // PBGSZ
    "FPBGSZ",      // FPBGSZ
    "RPBGSZ",      // RPBGSZ
    "FRPBGSZ",     // FRPBGSZ
    "LGSZ",        // LGSZ
    "FLGSZ",       // FLGSZ
    "RLGSZ",       // RLGSZ
    "FRLGSZ",      // FRLGSZ
    "PLGSZ",       // PLGSZ
    "FPLGSZ",      // FPLGSZ
    "RPLGSZ",      // RPLGSZ
    "FRPLGSZ",     // FRPLGSZ
    "BLGSZ",       // BLGSZ
    "FBLGSZ",      // FBLGSZ
    "RBLGSZ",      // RBLGSZ
    "FRBLGSZ",     // FRBLGSZ
    "PBLGSZ",      // PBLGSZ
    "FPBLGSZ",     // FPBLGSZ
    "RPBLGSZ",     // RPBLGSZ
    "FRPBLGSZ",    // FRPBLGSZ
    "TSZ",         // TSZ
    "FTSZ",        // FTSZ
    "RTSZ",        // RTSZ
    "FRTSZ",       // FRTSZ
    "PTSZ",        // PTSZ
    "FPTSZ",       // FPTSZ
    "RPTSZ",       // RPTSZ
    "FRPTSZ",      // FRPTSZ
    "BTSZ",        // BTSZ
    "FBTSZ",       // FBTSZ
    "RBTSZ",       // RBTSZ
    "FRBTSZ",      // FRBTSZ
    "PBTSZ",       // PBTSZ
    "FPBTSZ",      // FPBTSZ
    "RPBTSZ",      // RPBTSZ
    "FRPBTSZ",     // FRPBTSZ
    "LTSZ",        // LTSZ
    "FLTSZ",       // FLTSZ
    "RLTSZ",       // RLTSZ
    "FRLTSZ",      // FRLTSZ
    "PLTSZ",       // PLTSZ
    "FPLTSZ",      // FPLTSZ
    "RPLTSZ",      // RPLTSZ
    "FRPLTSZ",     // FRPLTSZ
    "BLTSZ",       // BLTSZ
    "FBLTSZ",      // FBLTSZ
    "RBLTSZ",      // RBLTSZ
    "FRBLTSZ",     // FRBLTSZ
    "PBLTSZ",      // PBLTSZ
    "FPBLTSZ",     // FPBLTSZ
    "RPBLTSZ",     // RPBLTSZ
    "FRPBLTSZ",    // FRPBLTSZ
    "GTSZ",        // GTSZ
    "FGTSZ",       // FGTSZ
    "RGTSZ",       // RGTSZ
    "FRGTSZ",      // FRGTSZ
    "PGTSZ",       // PGTSZ
    "FPGTSZ",      // FPGTSZ
    "RPGTSZ",      // RPGTSZ
    "FRPGTSZ",     // FRPGTSZ
    "BGTSZ",       // BGTSZ
    "FBGTSZ",      // FBGTSZ
    "RBGTSZ",      // RBGTSZ
    "FRBGTSZ",     // FRBGTSZ
    "PBGTSZ",      // PBGTSZ
    "FPBGTSZ",     // FPBGTSZ
    "RPBGTSZ",     // RPBGTSZ
    "FRPBGTSZ",    // FRPBGTSZ
    "LGTSZ",       // LGTSZ
    "FLGTSZ",      // FLGTSZ
    "RLGTSZ",      // RLGTSZ
    "FRLGTSZ",     // FRLGTSZ
    "PLGTSZ",      // PLGTSZ
    "FPLGTSZ",     // FPLGTSZ
    "RPLGTSZ",     // RPLGTSZ
    "FRPLGTSZ",    // FRPLGTSZ
    "BLGTSZ",      // BLGTSZ
    "FBLGTSZ",     // FBLGTSZ
    "RBLGTSZ",     // RBLGTSZ
    "FRBLGTSZ",    // FRBLGTSZ
    "PBLGTSZ",     // PBLGTSZ
    "FPBLGTSZ",    // FPBLGTSZ
    "RPBLGTSZ",    // RPBLGTSZ
    "FRPBLGTSZ",   // FRPBLGTSZ
    "DZ",          // DZ
    "FDZ",         // FDZ
    "RDZ",         // RDZ
    "FRDZ",        // FRDZ
    "PDZ",         // PDZ
    "FPDZ",        // FPDZ
    "RPDZ",        // RPDZ
    "FRPDZ",       // FRPDZ
    "BDZ",         // BDZ
    "FBDZ",        // FBDZ
    "RBDZ",        // RBDZ
    "FRBDZ",       // FRBDZ
    "NDZ",         // PBDZ
    "FPBDZ",       // FPBDZ
    "RPBDZ",       // RPBDZ
    "FRPBDZ",      // FRPBDZ
    "LDZ",         // LDZ
    "FLDZ",        // FLDZ
    "RLDZ",        // RLDZ
    "FRLDZ",       // FRLDZ
    "PLDZ",        // PLDZ
    "FPLDZ",       // FPLDZ
    "RPLDZ",       // RPLDZ
    "FRPLDZ",      // FRPLDZ
    "BLDZ",        // BLDZ
    "FBLDZ",       // FBLDZ
    "RBLDZ",       // RBLDZ
    "FRBLDZ",      // FRBLDZ
    "PBLDZ",       // PBLDZ
    "FPBLDZ",      // FPBLDZ
    "RPBLDZ",      // RPBLDZ
    "FRPBLDZ",     // FRPBLDZ
    "GDZ",         // GDZ
    "FGDZ",        // FGDZ
    "RGDZ",        // RGDZ
    "FRGDZ",       // FRGDZ
    "PGDZ",        // PGDZ
    "FPGDZ",       // FPGDZ
    "RPGDZ",       // RPGDZ
    "FRPGDZ",      // FRPGDZ
    "BGDZ",        // BGDZ
    "FBGDZ",       // FBGDZ
    "RBGDZ",       // RBGDZ
    "FRBGDZ",      // FRBGDZ
    "PBGDZ",       // PBGDZ
    "FPBGDZ",      // FPBGDZ
    "RPBGDZ",      // RPBGDZ
    "FRPBGDZ",     // FRPBGDZ
    "LGDZ",        // LGDZ
    "FLGDZ",       // FLGDZ
    "RLGDZ",       // RLGDZ
    "FRLGDZ",      // FRLGDZ
    "PLGDZ",       // PLGDZ
    "FPLGDZ",      // FPLGDZ
    "RPLGDZ",      // RPLGDZ
    "FRPLGDZ",     // FRPLGDZ
    "BLGDZ",       // BLGDZ
    "FBLGDZ",      // FBLGDZ
    "RBLGDZ",      // RBLGDZ
    "FRBLGDZ",     // FRBLGDZ
    "PBLGDZ",      // PBLGDZ
    "FPBLGDZ",     // FPBLGDZ
    "RPBLGDZ",     // RPBLGDZ
    "FRPBLGDZ",    // FRPBLGDZ
    "TDZ",         // TDZ
    "FTDZ",        // FTDZ
    "RTDZ",        // RTDZ
    "FRTDZ",       // FRTDZ
    "PTDZ",        // PTDZ
    "FPTDZ",       // FPTDZ
    "RPTDZ",       // RPTDZ
    "FRPTDZ",      // FRPTDZ
    "BTDZ",        // BTDZ
    "FBTDZ",       // FBTDZ
    "RBTDZ",       // RBTDZ
    "FRBTDZ",      // FRBTDZ
    "PBTDZ",       // PBTDZ
    "FPBTDZ",      // FPBTDZ
    "RPBTDZ",      // RPBTDZ
    "FRPBTDZ",     // FRPBTDZ
    "LTDZ",        // LTDZ
    "FLTDZ",       // FLTDZ
    "RLTDZ",       // RLTDZ
    "FRLTDZ",      // FRLTDZ
    "PLTDZ",       // PLTDZ
    "FPLTDZ",      // FPLTDZ
    "RPLTDZ",      // RPLTDZ
    "FRPLTDZ",     // FRPLTDZ
    "BLTDZ",       // BLTDZ
    "FBLTDZ",      // FBLTDZ
    "RBLTDZ",      // RBLTDZ
    "FRBLTDZ",     // FRBLTDZ
    "PBLTDZ",      // PBLTDZ
    "FPBLTDZ",     // FPBLTDZ
    "RPBLTDZ",     // RPBLTDZ
    "FRPBLTDZ",    // FRPBLTDZ
    "GTDZ",        // GTDZ
    "FGTDZ",       // FGTDZ
    "RGTDZ",       // RGTDZ
    "FRGTDZ",      // FRGTDZ
    "PGTDZ",       // PGTDZ
    "FPGTDZ",      // FPGTDZ
    "RPGTDZ",      // RPGTDZ
    "FRPGTDZ",     // FRPGTDZ
    "BGTDZ",       // BGTDZ
    "FBGTDZ",      // FBGTDZ
    "RBGTDZ",      // RBGTDZ
    "FRBGTDZ",     // FRBGTDZ
    "PBGTDZ",      // PBGTDZ
    "FPBGTDZ",     // FPBGTDZ
    "RPBGTDZ",     // RPBGTDZ
    "FRPBGTDZ",    // FRPBGTDZ
    "LGTDZ",       // LGTDZ
    "FLGTDZ",      // FLGTDZ
    "RLGTDZ",      // RLGTDZ
    "FRLGTDZ",     // FRLGTDZ
    "PLGTDZ",      // PLGTDZ
    "FPLGTDZ",     // FPLGTDZ
    "RPLGTDZ",     // RPLGTDZ
    "FRPLGTDZ",    // FRPLGTDZ
    "BLGTDZ",      // BLGTDZ
    "FBLGTDZ",     // FBLGTDZ
    "RBLGTDZ",     // RBLGTDZ
    "FRBLGTDZ",    // FRBLGTDZ
    "PBLGTDZ",     // PBLGTDZ
    "FPBLGTDZ",    // FPBLGTDZ
    "RPBLGTDZ",    // RPBLGTDZ
    "FRPBLGTDZ",   // FRPBLGTDZ
    "SDZ",         // SDZ
    "FSDZ",        // FSDZ
    "RSDZ",        // RSDZ
    "FRSDZ",       // FRSDZ
    "PSDZ",        // PSDZ
    "FPSDZ",       // FPSDZ
    "RPSDZ",       // RPSDZ
    "FRPSDZ",      // FRPSDZ
    "BSDZ",        // BSDZ
    "FBSDZ",       // FBSDZ
    "RBSDZ",       // RBSDZ
    "FRBSDZ",      // FRBSDZ
    "PBSDZ",       // PBSDZ
    "FPBSDZ",      // FPBSDZ
    "RPBSDZ",      // RPBSDZ
    "FRPBSDZ",     // FRPBSDZ
    "LSDZ",        // LSDZ
    "FLSDZ",       // FLSDZ
    "RLSDZ",       // RLSDZ
    "FRLSDZ",      // FRLSDZ
    "PLSDZ",       // PLSDZ
    "FPLSDZ",      // FPLSDZ
    "RPLSDZ",      // RPLSDZ
    "FRPLSDZ",     // FRPLSDZ
    "BLSDZ",       // BLSDZ
    "FBLSDZ",      // FBLSDZ
    "RBLSDZ",      // RBLSDZ
    "FRBLSDZ",     // FRBLSDZ
    "PBLSDZ",      // PBLSDZ
    "FPBLSDZ",     // FPBLSDZ
    "RPBLSDZ",     // RPBLSDZ
    "FRPBLSDZ",    // FRPBLSDZ
    "GSDZ",        // GSDZ
    "FGSDZ",       // FGSDZ
    "RGSDZ",       // RGSDZ
    "FRGSDZ",      // FRGSDZ
    "PGSDZ",       // PGSDZ
    "FPGSDZ",      // FPGSDZ
    "RPGSDZ",      // RPGSDZ
    "FRPGSDZ",     // FRPGSDZ
    "BGSDZ",       // BGSDZ
    "FBGSDZ",      // FBGSDZ
    "RBGSDZ",      // RBGSDZ
    "FRBGSDZ",     // FRBGSDZ
    "PBGSDZ",      // PBGSDZ
    "FPBGSDZ",     // FPBGSDZ
    "RPBGSDZ",     // RPBGSDZ
    "FRPBGSDZ",    // FRPBGSDZ
    "LGSDZ",       // LGSDZ
    "FLGSDZ",      // FLGSDZ
    "RLGSDZ",      // RLGSDZ
    "FRLGSDZ",     // FRLGSDZ
    "PLGSDZ",      // PLGSDZ
    "FPLGSDZ",     // FPLGSDZ
    "RPLGSDZ",     // RPLGSDZ
    "FRPLGSDZ",    // FRPLGSDZ
    "BLGSDZ",      // BLGSDZ
    "FBLGSDZ",     // FBLGSDZ
    "RBLGSDZ",     // RBLGSDZ
    "FRBLGSDZ",    // FRBLGSDZ
    "PBLGSDZ",     // PBLGSDZ
    "FPBLGSDZ",    // FPBLGSDZ
    "RPBLGSDZ",    // RPBLGSDZ
    "FRPBLGSDZ",   // FRPBLGSDZ
    "TSDZ",        // TSDZ
    "FTSDZ",       // FTSDZ
    "RTSDZ",       // RTSDZ
    "FRTSDZ",      // FRTSDZ
    "PTSDZ",       // PTSDZ
    "FPTSDZ",      // FPTSDZ
    "RPTSDZ",      // RPTSDZ
    "FRPTSDZ",     // FRPTSDZ
    "BTSDZ",       // BTSDZ
    "FBTSDZ",      // FBTSDZ
    "RBTSDZ",      // RBTSDZ
    "FRBTSDZ",     // FRBTSDZ
    "PBTSDZ",      // PBTSDZ
    "FPBTSDZ",     // FPBTSDZ
    "RPBTSDZ",     // RPBTSDZ
    "FRPBTSDZ",    // FRPBTSDZ
    "LTSDZ",       // LTSDZ
    "FLTSDZ",      // FLTSDZ
    "RLTSDZ",      // RLTSDZ
    "FRLTSDZ",     // FRLTSDZ
    "PLTSDZ",      // PLTSDZ
    "FPLTSDZ",     // FPLTSDZ
    "RPLTSDZ",     // RPLTSDZ
    "FRPLTSDZ",    // FRPLTSDZ
    "BLTSDZ",      // BLTSDZ
    "FBLTSDZ",     // FBLTSDZ
    "RBLTSDZ",     // RBLTSDZ
    "FRBLTSDZ",    // FRBLTSDZ
    "PBLTSDZ",     // PBLTSDZ
    "FPBLTSDZ",    // FPBLTSDZ
    "RPBLTSDZ",    // RPBLTSDZ
    "FRPBLTSDZ",   // FRPBLTSDZ
    "GTSDZ",       // GTSDZ
    "FGTSDZ",      // FGTSDZ
    "RGTSDZ",      // RGTSDZ
    "FRGTSDZ",     // FRGTSDZ
    "PGTSDZ",      // PGTSDZ
    "FPGTSDZ",     // FPGTSDZ
    "RPGTSDZ",     // RPGTSDZ
    "FRPGTSDZ",    // FRPGTSDZ
    "BGTSDZ",      // BGTSDZ
    "FBGTSDZ",     // FBGTSDZ
    "RBGTSDZ",     // RBGTSDZ
    "FRBGTSDZ",    // FRBGTSDZ
    "PBGTSDZ",     // PBGTSDZ
    "FPBGTSDZ",    // FPBGTSDZ
    "RPBGTSDZ",    // RPBGTSDZ
    "FRPBGTSDZ",   // FRPBGTSDZ
    "LGTSDZ",      // LGTSDZ
    "FLGTSDZ",     // FLGTSDZ
    "RLGTSDZ",     // RLGTSDZ
    "FRLGTSDZ",    // FRLGTSDZ
    "PLGTSDZ",     // PLGTSDZ
    "FPLGTSDZ",    // FPLGTSDZ
    "RPLGTSDZ",    // RPLGTSDZ
    "FRPLGTSDZ",   // FRPLGTSDZ
    "BLGTSDZ",     // BLGTSDZ
    "FBLGTSDZ",    // FBLGTSDZ
    "RBLGTSDZ",    // RBLGTSDZ
    "FRBLGTSDZ",   // FRBLGTSDZ
    "PBLGTSDZ",    // PBLGTSDZ
    "FPBLGTSDZ",   // FPBLGTSDZ
    "RPBLGTSDZ",   // RPBLGTSDZ
    "FRPBLGTSDZ",  // FRPBLGTSDZ
];
